print("==============================") 
print("= NAMA    : SHOBAHUS SOLICHIN ") 
print("= NIM     : 312010076         ")
print("= KELAS   : TI.20 A.1         ") 
print("==============================") 

print("Please enter your full name : SHOBAHUS SOLICHIN ")
fullname=input()
print("Please enter nickname : SHOBA")
nickname=input()
print("Please enter your NPM : 312010076")
npm=input()
print("Please enter place of birth : JAKARTA")
pob=input()
print("Please enter date of birth : 20 ")
date=input()
print("Please enter your month of birth : DECEMBER")
month=input()
print("Please enter year of birth : 2001")
year=input()
print("Please enter your phone number : 081297995301")
phone=input()
print("Please enter your address : Perum.Citra Graha Prima")
address=input()

dob=input("2020-year")

print("\n\n Assalamu'alaikum.")
print("Let me introduce my self, my name is {SHOBAHUS SOLICHIN}, but you can call me {SHOBA}, my NPM {312010076}, I was born in {JAKARTA} and iam {2020} years old, I am very glad if you want to invite my house in {Perum.Citra Graha Prima}, So don't forget to call me before with the number {0812397995301}, \n\n Thanks you ssss")